export const progressTrackerTranslations = {
    en: {
        treatmentProgress: 'Treatment Progress',
        caseAdded: 'Case Added',
        clinicalDiagnosis: 'Diagnosis',
        reviewedBySupervisor: 'Reviewed',
        treatment: 'Treatment',
        caseClosed: 'Completed',
        aiExam: 'via AI Exam',
        byDoctor: 'By Supervisor',
        by: 'by',
        activeCare: 'Active care',
        completed: 'Finished',
        clinicalExam: 'Clinical exam',
        verifiedReview: 'Verified review',
        doctor: 'Doctor',
        student: 'Student',
        patient: 'Patient',
    },
    ar: {
        treatmentProgress: 'تقدم العلاج',
        caseAdded: 'تم إضافة الحالة',
        clinicalDiagnosis: 'التشخيص',
        reviewedBySupervisor: 'مراجعة المشرف',
        treatment: 'العلاج',
        caseClosed: 'مكتملة',
        aiExam: 'عبر فحص AI',
        byDoctor: 'بواسطة المشرف',
        by: 'بواسطة',
        activeCare: 'رعاية نشطة',
        completed: 'منتهية',
        clinicalExam: 'فحص سريري',
        verifiedReview: 'مراجعة معتمدة',
        doctor: 'طبيب',
        student: 'طالب',
        patient: 'مريض',
    },
};
